# Generated by Django 3.1.4 on 2021-01-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.host'),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='categorygroupmedium',
            name='category_group_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygrouptop'),
        ),
        migrations.AddField(
            model_name='categorygroupbottom',
            name='category_group_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygroupmedium'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_group_bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygroupbottom'),
        ),
    ]
