# Generated by Django 3.1.4 on 2021-01-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210104_1252'),
        ('product', '0002_auto_20210107_0946'),
    ]

    operations = [
    ]
