# Generated by Django 3.1.4 on 2021-01-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_review_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
