# Generated by Django 3.1.4 on 2020-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authentication_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
