# Generated by Django 3.1.4 on 2020-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='hi', max_length=20),
            preserve_default=False,
        ),
    ]
