# Generated by Django 3.1.4 on 2020-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201231_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
