# Generated by Django 3.1.4 on 2020-12-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201230_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
