# Generated by Django 3.1.4 on 2021-01-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201230_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupBottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_group_bottoms',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_group_mediums',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_group_tops',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_bottom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_medium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_top',
        ),
        migrations.AlterField(
            model_name='product',
            name='five_star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='gathering_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        # migrations.DeleteModel(
        #     name='CategoryBottom',
        # ),
        migrations.DeleteModel(
            name='CategoryMedium',
        ),
        migrations.DeleteModel(
            name='CategoryTop',
        ),
        migrations.AddField(
            model_name='categorygroupmedium',
            name='category_group_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygrouptop'),
        ),
        migrations.AddField(
            model_name='categorygroupbottom',
            name='category_group_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygroupmedium'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_group_bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorygroupbottom'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.category'),
            preserve_default=False,
        ),
    ]
